# Generated by Django 4.2 on 2023-04-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_orderitem_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
