# Generated by Django 4.2 on 2023-04-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='book_warehouse_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderitembookitem',
            name='book_item_id',
        ),
        migrations.RemoveField(
            model_name='orderitembookitem',
            name='order_item_id',
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderItemBookItem',
        ),
    ]
