# Generated by Django 4.2 on 2023-04-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_api', '0003_order_orderitembookitem_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookitem',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='book_warehouse_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderitembookitem',
            name='book_item_id',
        ),
        migrations.RemoveField(
            model_name='orderitembookitem',
            name='order_item_id',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='OrderItemBookItem',
        ),
    ]
